apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-admin
    receivers:
      - uid: email-admin
        type: email
        settings:
          addresses: ${GRAFANA_ADMIN_EMAIL}
          singleEmail: true
        disableResolveMessage: false
