apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
  - name: Prometheus
    uid: grafanacloud-prom
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 30s

  - name: Loki
    uid: grafanacloud-logs
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      timeout: 300
      maxLines: 5000
