{
 "title": "Docker overview",
 "tags": [ "docker-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Asserts environment",
    "query": "label_values(asserts:mixin_workload_job, asserts_env)"
   },
   {
    "name": "site",
    "label": "Asserts site",
    "query": "label_values(asserts:mixin_workload_job{asserts_env=~\"$env\"}, asserts_site)"
   },
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(container_last_seen{job!=\"kubelet\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(container_last_seen{job!=\"kubelet\",job=~\"$job\"}, instance)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(container_last_seen{job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Integration Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Shows if metrics are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"$job\"} == 1) > 0) and (absent(absent(machine_scrape_error{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"$job\"})))) or vector(0) and on() ((count(up{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"$job\"}) > 0) and (absent(machine_scrape_error{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"$job\"})))\n"
    }
   ]
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"$job\"} == 1) > 0) and (absent(absent(machine_scrape_error{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"$job\"})))) or vector(0) and on() ((count(up{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"$job\"}) > 0) and (absent(machine_scrape_error{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"$job\"})))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "text",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center\">1.4.0</p>"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 3 } },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Total number of running containers last seen by the exporter.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count(container_last_seen{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\",job=~\"$job\",instance=~\"$instance\", name!=\"\"})",
     "legendFormat": "{{instance}}: Containers"
    }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "description": "Total number of distinct images found across running containers.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "count (sum by (image) (container_last_seen{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\",job=~\"$job\",instance=~\"$instance\", name!=\"\"}))",
     "legendFormat": "{{instance}}: Images"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "CPU usage (avg): Cpu time consumed in seconds by container.  \n",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,instance, name) (rate(container_cpu_usage_seconds_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\",job=~\"$job\",instance=~\"$instance\", name!=\"\"}[$__rate_interval])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory reserved",
   "type": "stat",
   "description": "Memory reserved by the containers on the machine.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  container_spec_memory_reservation_limit_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\",job=~\"$job\",instance=~\"$instance\", name!=\"\"}\n  )\n/ \navg(\n    machine_memory_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\",job=~\"$job\",instance=~\"$instance\"}\n) * 100\n",
     "legendFormat": "{{instance}}: Memory reserved"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "stat",
   "description": "Memory used by all containers out of machine total.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  sum by (instance) (container_memory_usage_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\",job=~\"$job\",instance=~\"$instance\", name!=\"\"})\n  /\n  avg by (instance) (machine_memory_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\",job=~\"$job\",instance=~\"$instance\"})\n) * 100\n",
     "legendFormat": "{{instance}}: Memory used"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 20, "y": 8 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU time consumed in seconds by container.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\n  rate(container_cpu_usage_seconds_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Current memory usage in bytes, including all memory regardless of when it was accessed by container.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 16 } },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "received (avg): Cumulative count of bytes received.  \n\ntransmitted (avg): Cumulative count of bytes transmitted.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 *\n  rate(container_network_receive_bytes_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])\n",
     "legendFormat": "{{name}}/{{interface}} receive"
    },
    {
     "expr": "8 *\n  rate(container_network_transmit_bytes_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])\n",
     "legendFormat": "{{name}}/{{interface}} transmit"
    }
   ]
  },
  {
   "title": "Network errors and drops",
   "type": "timeseries",
   "description": "drops received (avg): Number of packets received and dropped.  \n\ndrops transmitted (avg): Number of packets dropped while transmitting.  \n\nerrors received (avg): Number of packets received with errors.  \n\nerrors transmitted (avg): Number of packets transmitted with errors.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_dropped_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{interface}} rx drops"
    },
    {
     "expr": "rate(container_network_transmit_packets_dropped_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{interface}} tx drops"
    },
    {
     "expr": "rate(container_network_receive_errors_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{interface}} rx errors"
    },
    {
     "expr": "rate(container_network_transmit_errors_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{interface}} tx errors"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 24 } },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "Disk space usage (avg): Disk space usage in bytes.  \n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{name}}/{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Disk reads (avg): The number of read requests per second for the device/volume.  \n\nDisk writes (avg): The number of write requests per second for the device/volume.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{device}} read"
    },
    {
     "expr": "rate(container_fs_writes_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job!=\"kubelet\", name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{device}} write"
    }
   ]
  }
 ]
}